services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVELOPMENT: 1
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    tty: true
